//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservations2
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Forms;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Reservations = new HashSet<Reservation>();
        }
        public static bool newCustomer(DataGridView dGV, int row)
        {
            try
            {
                HotelResvEntities Db = new HotelResvEntities();

                Customer Cs = new Customer();
                Cs.Customer_guid = Guid.NewGuid();
                Cs.Customer_Number = Int32.Parse(dGV[0, row].Value.ToString());
                Cs.Customer_FName = dGV[2, row].Value.ToString();
                Cs.Customer_LName = dGV[3, row].Value.ToString();
                Cs.Customer_addr1 = dGV[4, row].Value.ToString();
                Cs.Customer_addr2 = dGV[5, row].Value.ToString();
                Cs.Customer_city = dGV[6, row].Value.ToString();
                Cs.Customer_state = dGV[7, row].Value.ToString();
                Cs.Customer_zip = dGV[8, row].Value.ToString();
                Cs.Customer_phone = dGV[9, row].Value.ToString();
                Cs.Customer_discounts = dGV[10, row].Value.ToString();

                Db.Customers.Add(Cs);
                Db.SaveChanges();

                return true;
            }
            catch
            {
                return false;
            }
        }
    
        public System.Guid Customer_guid { get; set; }
        public int Customer_Number { get; set; }
        public string Customer_FName { get; set; }
        public string Customer_LName { get; set; }
        public string Customer_addr1 { get; set; }
        public string Customer_addr2 { get; set; }
        public string Customer_city { get; set; }
        public string Customer_state { get; set; }
        public string Customer_zip { get; set; }
        public string Customer_phone { get; set; }
        public Nullable<int> Customer_last_room_type { get; set; }
        public string Customer_discounts { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
