//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservations2
{
    using System;
    using System.Collections.Generic;
    
    public partial class roomView
    {
        public System.Guid Room_guid { get; set; }
        public Nullable<int> Room_number { get; set; }
        public string RoomType_Name { get; set; }
        public Nullable<decimal> RoomType_Price { get; set; }
        public Nullable<bool> Room_Vacant { get; set; }
        public Nullable<bool> Room_CheckedIn { get; set; }
    }
}
